print("This will be a selfie...mabey")
print("Lol")
print("Bowl")
print("WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
print("Do a barrel.")
print("In the 30's you had to box your dad and win to earn dinner. There were starving kids during that time. ")